# if merged in master, create tag & release

name: echo branch name
on: 
  pull_request:
    branches: 
      - master
    types: 
      - closed
jobs:
  if_merged_in_master: 
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name : 'Get Previous tag'
        id : previoustag
        uses : WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: "0.0.0"
        
      - name: 'Get next minor version'
        id: semvers
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          version: ${{ steps.previoustag.outputs.tag }}
          type: "minor"
        
      - name: 'Create release'
        uses: WyriHaximus/github-action-create-release@v1
        with:
          tag: ${{ steps.semvers.outputs.minor }}
          name: ${{ steps.semvers.outputs.minor }}
          body: "release ${{ steps.semvers.outputs.minor }}"
        
