# if merged in master, create tag & release

name: echo branch name
on: 
  pull_request:
    branches: 
      - master
    types: 
      - closed
jobs:
  draft: 
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
